version: "3.9"

services:
  vector_db:
    image: qdrant/qdrant:v1.8.4
    container_name: smartchef_vectordb
    ports:
      - "6333:6333"
    volumes:
      - ./vector-db/data:/qdrant/storage
  postgres:
    image: postgres:17
    container_name: smartchef_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

